export type DetailItemData = {
  id: string;
  title: string;
  description?: string;
  photoUri?: string;
  photoStoragePath?: string;
  phone?: string;
  category?: string;
  price?: string;
  priceLabel?: string;
  address?: string;
  status?: string;
  votesCount?: number;
  hasVoted?: boolean;
  userId?: string;
  ownerAvatarUri?: string;
  createdAt?: string;
  sourceType: string;
  sourceId: string;
};
