export const CHAIKA_NEWS_SOURCES = [
  {
    name: 'Українська правда',
    url: 'https://www.pravda.com.ua/',
    type: 'media',
    region: 'ukraine',
    mode: 'rss',
    rss: 'https://www.pravda.com.ua/rss/view_news/',
    priority: 5,
  },
  {
    name: 'ДСНС України',
    url: 'https://dsns.gov.ua/',
    type: 'official',
    region: 'ukraine',
    mode: 'manual',
    priority: 4,
  },
  {
    name: 'Київська ОВА',
    url: 'https://koda.gov.ua/',
    type: 'official',
    region: 'kyiv_region',
    mode: 'rss',
    rss: 'https://www.koda.gov.ua/rss',
    priority: 10,
  },
  {
    name: 'Національна поліція України',
    url: 'https://www.npu.gov.ua/',
    type: 'official',
    region: 'ukraine',
    mode: 'manual',
    priority: 4,
  },
  {
    name: 'Суспільне',
    url: 'https://suspilne.media/',
    type: 'media',
    region: 'kyiv',
    mode: 'rss',
    rss: 'https://suspilne.media/kyiv/rss/all.rss',
    priority: 10,
  },
  {
    name: 'ТСН',
    url: 'https://tsn.ua/',
    type: 'media',
    region: 'ukraine',
    mode: 'manual',
    priority: 3,
  },
  {
    name: 'Сегодня',
    url: 'https://www.segodnya.ua/',
    type: 'media',
    region: 'ukraine',
    mode: 'manual',
    priority: 2,
  },
  {
    name: 'Bucha City',
    url: 'https://bucha.com.ua/',
    type: 'local',
    region: 'bucha',
    mode: 'manual',
    priority: 10,
  },
  {
    name: 'Irpin Online',
    url: 'https://irpin.online/',
    type: 'local',
    region: 'irpin',
    mode: 'manual',
    priority: 7,
  },
  {
    name: 'Big Kyiv',
    url: 'https://bigkyiv.com.ua/',
    type: 'local',
    region: 'kyiv',
    mode: 'rss',
    rss: 'https://bigkyiv.com.ua/feed/',
    priority: 9,
  },
  {
    name: 'KyivRegion.info',
    url: 'https://kyivregion.info/',
    type: 'local',
    region: 'kyiv_region',
    mode: 'manual',
    priority: 6,
  },
  {
    name: 'Вечірній Київ',
    url: 'https://vechirniy.kyiv.ua/',
    type: 'local',
    region: 'kyiv',
    mode: 'rss',
    rss: 'https://vechirniy.kyiv.ua/rss/',
    priority: 9,
  },
  {
    name: 'Київський портал',
    url: 'https://kyivcity.gov.ua/',
    type: 'official',
    region: 'kyiv',
    mode: 'rss',
    rss: 'https://kyivcity.gov.ua/news/rss/',
    priority: 10,
  },
  {
    name: 'kyivoperativ',
    url: 'https://t.me/kyivoperativ',
    type: 'telegram',
    region: 'kyiv',
    mode: 'manual',
    priority: 8,
  },
  {
    name: 'kievreal1',
    url: 'https://t.me/kievreal1',
    type: 'telegram',
    region: 'kyiv',
    mode: 'manual',
    priority: 7,
  },
  {
    name: 'truexanewsua',
    url: 'https://t.me/truexanewsua',
    type: 'telegram',
    region: 'ukraine',
    mode: 'manual',
    priority: 5,
  },
  {
    name: 'bucha_live',
    url: 'https://t.me/bucha_live',
    type: 'telegram',
    region: 'bucha',
    mode: 'manual',
    priority: 10,
  },
  {
    name: 'irpin_daily',
    url: 'https://t.me/irpin_daily',
    type: 'telegram',
    region: 'irpin',
    mode: 'manual',
    priority: 7,
  },
  {
    name: 'kyivregion_news',
    url: 'https://t.me/kyivregion_news',
    type: 'telegram',
    region: 'kyiv_region',
    mode: 'manual',
    priority: 8,
  },
  {
    name: 'Facebook Chayka Kyiv',
    url: 'https://www.facebook.com/groups/chayka.kiev/',
    type: 'facebook',
    region: 'chaika',
    mode: 'manual',
    priority: 10,
  },
  {
    name: 'Facebook Bucha City',
    url: 'https://www.facebook.com/groups/bucha.city/',
    type: 'facebook',
    region: 'bucha',
    mode: 'manual',
    priority: 8,
  },
  {
    name: 'Facebook Irpin Community',
    url: 'https://www.facebook.com/groups/irpin.community/',
    type: 'facebook',
    region: 'irpin',
    mode: 'manual',
    priority: 6,
  },
  {
    name: 'Facebook Kyiv Oblast',
    url: 'https://www.facebook.com/groups/kyivoblast/',
    type: 'facebook',
    region: 'kyiv_region',
    mode: 'manual',
    priority: 6,
  },
  {
    name: 'Instagram Kyiv Operativ',
    url: 'https://www.instagram.com/kyivoperativ/',
    type: 'instagram',
    region: 'kyiv',
    mode: 'manual',
    priority: 6,
  },
  {
    name: 'Instagram Truexa Kyiv',
    url: 'https://www.instagram.com/truexa_kyiv/',
    type: 'instagram',
    region: 'kyiv',
    mode: 'manual',
    priority: 5,
  },
  {
    name: 'Instagram Bucha Live',
    url: 'https://www.instagram.com/bucha_live/',
    type: 'instagram',
    region: 'bucha',
    mode: 'manual',
    priority: 5,
  },
  {
    name: 'Google Maps',
    url: 'https://www.google.com/maps',
    type: 'maps',
    region: 'chaika',
    mode: 'manual',
    priority: 7,
  },
  {
    name: 'Waze',
    url: 'https://www.waze.com/',
    type: 'maps',
    region: 'kyiv_region',
    mode: 'manual',
    priority: 7,
  },
  {
    name: 'OLX',
    url: 'https://www.olx.ua/',
    type: 'market',
    region: 'chaika',
    mode: 'manual',
    priority: 4,
  },
  {
    name: 'ChaikaUA',
    url: 'https://chaika-ua.netlify.app',
    type: 'local',
    region: 'chaika',
    mode: 'manual',
    priority: 10,
  },
  {
    name: 'Чати ЖК (Viber / Telegram жильців)',
    url: 'manual',
    type: 'community',
    region: 'chaika',
    mode: 'manual',
    priority: 10,
  },
];

export const ACTIVE_RSS_SOURCES = CHAIKA_NEWS_SOURCES
  .filter((source) => source.mode === 'rss' && source.rss)
  .sort((a, b) => b.priority - a.priority)
  .map((source) => source.rss);
